"""
Bet and betting signal data models.

These models represent betting decisions and executed bets.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from src.models.market import Sport


class BetType(str, Enum):
    """Type of bet - back or lay."""

    BACK = "BACK"
    LAY = "LAY"


class BetStatus(str, Enum):
    """Status of a bet through its lifecycle."""

    PENDING = "PENDING"  # Signal generated, not yet placed
    PLACED = "PLACED"  # Order placed on exchange
    MATCHED = "MATCHED"  # Fully matched
    PARTIALLY_MATCHED = "PARTIALLY_MATCHED"
    CANCELLED = "CANCELLED"
    SETTLED = "SETTLED"  # Result known
    VOIDED = "VOIDED"


class BetResult(str, Enum):
    """Result of a settled bet."""

    WON = "WON"
    LOST = "LOST"
    VOID = "VOID"


@dataclass
class BetSignal:
    """
    A betting signal generated by a strategy.

    This represents an opportunity identified by a strategy,
    before any bet has been placed.
    """

    market_id: str
    selection_id: int
    selection_name: str
    bet_type: BetType
    odds: float
    stake: float
    strategy: str

    # Analysis that led to this signal
    model_probability: Optional[float] = None
    implied_probability: Optional[float] = None
    edge: Optional[float] = None

    # Additional context
    sport: Optional[Sport] = None
    market_name: Optional[str] = None
    event_name: Optional[str] = None
    reason: str = ""

    # Timing
    signal_time: datetime = field(default_factory=datetime.utcnow)

    @property
    def potential_profit(self) -> float:
        """Calculate potential profit if bet wins."""
        if self.bet_type == BetType.BACK:
            return self.stake * (self.odds - 1)
        else:
            # Lay bet - profit is the stake if selection loses
            return self.stake

    @property
    def potential_loss(self) -> float:
        """Calculate potential loss if bet loses."""
        if self.bet_type == BetType.BACK:
            return self.stake
        else:
            # Lay bet - liability if selection wins
            return self.stake * (self.odds - 1)


@dataclass
class Bet:
    """
    A placed bet with full tracking information.

    Created when a BetSignal is executed (paper or live).
    """

    id: Optional[int] = None  # Database ID
    bet_ref: Optional[str] = None  # Betfair bet reference

    # Market and selection
    market_id: str = ""
    selection_id: int = 0
    selection_name: str = ""

    # Bet details
    strategy: str = ""
    bet_type: BetType = BetType.BACK
    requested_odds: float = 0.0
    matched_odds: float = 0.0
    stake: float = 0.0

    # Calculated values
    potential_profit: float = 0.0
    potential_loss: float = 0.0

    # Status tracking
    status: BetStatus = BetStatus.PENDING
    is_paper: bool = True

    # Settlement
    result: Optional[BetResult] = None
    profit_loss: float = 0.0
    commission: float = 0.0  # Betfair commission paid

    # Timestamps
    placed_at: datetime = field(default_factory=datetime.utcnow)
    matched_at: Optional[datetime] = None
    settled_at: Optional[datetime] = None

    # Additional context
    sport: Optional[Sport] = None
    event_name: Optional[str] = None

    @classmethod
    def from_signal(cls, signal: BetSignal, is_paper: bool = True) -> "Bet":
        """Create a Bet from a BetSignal."""
        return cls(
            market_id=signal.market_id,
            selection_id=signal.selection_id,
            selection_name=signal.selection_name,
            strategy=signal.strategy,
            bet_type=signal.bet_type,
            requested_odds=signal.odds,
            matched_odds=signal.odds,  # Assume matched at requested odds initially
            stake=signal.stake,
            potential_profit=signal.potential_profit,
            potential_loss=signal.potential_loss,
            status=BetStatus.PENDING,
            is_paper=is_paper,
            sport=signal.sport,
            event_name=signal.event_name,
            placed_at=datetime.utcnow(),
        )

    def settle(self, result: BetResult, commission_rate: float = 0.05) -> None:
        """
        Settle the bet with a result.

        Args:
            result: Win, lose, or void
            commission_rate: Betfair commission rate (default 5%)
        """
        self.result = result
        self.settled_at = datetime.utcnow()
        self.status = BetStatus.SETTLED

        if result == BetResult.WON:
            gross_profit = self.potential_profit
            self.commission = gross_profit * commission_rate
            self.profit_loss = gross_profit - self.commission
        elif result == BetResult.LOST:
            self.profit_loss = -self.potential_loss
            self.commission = 0.0
        else:
            # Void - return stake
            self.profit_loss = 0.0
            self.commission = 0.0

    @property
    def net_profit_loss(self) -> float:
        """Net P&L after commission."""
        return self.profit_loss


@dataclass
class OpenPosition:
    """Represents an open position that may need managing."""

    bet: Bet
    market_id: str
    selection_id: int
    current_odds: Optional[float] = None
    current_pl: float = 0.0  # Current P&L if closed now

    @property
    def is_in_profit(self) -> bool:
        """Check if position is currently profitable."""
        return self.current_pl > 0
